### ISSUE TITLE
Please allow support for loading and saving multiple icon resolutions

### ISSUE THREAD

**Issue by NicusorN5** [KyleTTucker/Paint.net-Icon-Creator#2]
Title is descriptive enough.

**Comment by Benman2785** [comment]
yep - we need to be able to save 16x16 & 256x256 - and all in between in one file ;)

**Comment by ghost** [comment]
I'd like to mention that [there's a separate plugin](https://forums.getpaint.net/topic/927-icon-cursor-and-animated-cursor-format-v37-may-2010/page/13/#comment-514467) that accounts for the sizes. I haven't tried saving as an ico yet, but importing a particular size worked.
